### ISSUE TITLE
 Exception Handling

### ISSUE THREAD

**Issue by l-we** [tamerh/xml-stream-parser#1]
goroutine  Does not end
```
<?xml version="1.0" encoding="UTF-8"?>
<bookstore>
    <book ISBN="10-000000-001">
        <title>The Iliad and The Odyssey</title>
        <price>12.95</price>
        <comments>
            <userComment rating="4">Best translation I've read.</userComment>
            <userComment rating="2">I like other versions better.</userComment>
        </comments>
        <description>Homer's two epics of the ancient world, The Iliad & The Odyssey, tell stories as riveting today as when they were written between the eighth and ninth century B.C.</description>
    </book>
    <book ISBN="10-000000-999">
        <title>Anthology of World Literature</title>
        <price>24.95</price>
        <comments>
            <userComment rating="3">Needs more modern literature.</userComment>
```

**Comment by tamerh** [comment]
you are right i tested only for valid xml. Now added panics for this situation.

**Comment by mhnatiuk** [comment]
Hi, I use your parser to process xml input that often isn't valid XML. Adding panic in Parse() unfortunately  prevents me from handling this error, which in my case is very easy: log it and ignore. SHould I just fork your repo and do it myself? I think that it would be better to somehow return the error - maybe on a second error channel?

**Comment by tamerh** [comment]
Hi, glad that you're using it. How about recovering the panic there is an example in the test. Is that help?
