### ISSUE TITLE
Can't get it to work?

### ISSUE THREAD

**Issue by abhilash2210** [tamerh/xml-stream-parser#13]
I have been trying to use this parser but even when I try the example code mentioned here, I can't get it to run. Any valid xml results in an invalid xml error because of EOF? What am I doing wrong?

**Comment by tamerh** [comment]
Both examples and tests are running for me and parser is used by other people. Could be related with your environment what is your os and version of GO? also which exact error you are getting?  Have you also checked the test cases?

**Comment by abhilash2210** [comment]
>    
```
        f, _ := os.Open("input.xml")
	br := bufio.NewReader(f)
	parser := xmlparser.NewXMLParser(br, "book", "journal")

	for xml := range parser.Stream() {
		if xml.Err !=nil {
			fmt.Println("xml.Err:", xml.Err);
                        return;
		}

		fmt.Println(xml.Childs["title"][0].InnerText)
		if xml.Name == "book" {
			fmt.Println(xml.Childs["comments"][0].Childs["userComment"][0].Attrs["rating"])
			fmt.Println(xml.Childs["comments"][0].Childs["userComment"][0].InnerText)
		}
	}
```
>    
```
Output: 
xml.Err: EOF
```

Test cases:

> 

```
github.com/tamerh/xml-stream-parser$ go test
--- FAIL: TestBasics (0.00s)
panic: Test failed result must be 2 [recovered]
	panic: Test failed result must be 2

goroutine 5 [running]:
testing.tRunner.func1(0xc0000ae100)
	/usr/local/go/src/testing/testing.go:792 +0x387
panic(0x532bc0, 0x58a0c0)
	/usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/tamerh/xml-stream-parser.TestBasics(0xc0000ae100)
	/go/src/github.com/tamerh/xml-stream-parser/xmlparser_test.go:38 +0x326d
testing.tRunner(0xc0000ae100, 0x5728a8)
	/usr/local/go/src/testing/testing.go:827 +0xbf
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:878 +0x35c
exit status 2
FAIL	github.com/tamerh/xml-stream-parser	0.004s
```

go version go1.11.5 linux/amd64

**Comment by tamerh** [comment]
parser may not work with the go1.11 see the issue #3.
you can try the older version of the parser version 1.1.3 without recent features and fixes.

**Comment by tamerh** [comment]
But I am going to check again the reason for not working with go1.11

**Comment by imirkin** [comment]
A little quick debugging shows this, not 100% sure if it's expected yet:

<pre>
(gdb) p element.Name
$12 = 0xc0000a20db "<tag1"
(gdb) p x.loopElements 
$13 = map[string]bool = {[0x568976 "tag1"] = true}
(gdb) n
142                             if _, found := x.loopElements[element.Name]; found {
</pre>

so obviously x.loopElements doesn't get hit because element.Name contains the "<".

**Comment by imirkin** [comment]
Looks like isCDATA unreads a byte, but it actually uses Peek() to read the first 2 bytes. So that unread should not be there. Removing it fixes the test, at least:

```
diff --git a/xmlparser.go b/xmlparser.go
index 9555b7b..72856a8 100644
--- a/xmlparser.go
+++ b/xmlparser.go
@@ -524,7 +524,7 @@ func (x *XMLParser) isCDATA() (bool, []byte, error) {
        }
 
        if b[0] != '!' {
-               x.unreadByte()
+               //x.unreadByte()
                return false, nil, nil
        }
 
```

**Comment by imirkin** [comment]
@tamerh I'm not sure why it'd be different for go1.12+, but that unreadByte really seems misplaced. What do you think?

**Comment by tamerh** [comment]
@imirkin thanks for spotting this yes seems that it is misplaced just trying to make sure. 

`Peek` method has changed in go1.12  

https://github.com/golang/go/blob/release-branch.go1.12/src/bufio/bufio.go
https://github.com/golang/go/blob/release-branch.go1.11/src/bufio/bufio.go

I assume in the go1.12 that misplaced line has no affect.

**Comment by imirkin** [comment]
Ah yeah, I see. Looks like starting from go1.12 Unread after Peek is a no-op, while in go1.11 it still did stuff.

So this bug doesn't matter for go1.12+, but runs into problems for go1.11-.

**Comment by tamerh** [comment]
Yes @imirkin I double checked. do you want to send a PR for the the fix?

**Comment by tamerh** [comment]
I tagged a new version as `v1.4.0`

**Comment by abhilash2210** [comment]
Thanks guys!
