### ISSUE TITLE
A potential missing edge case

### ISSUE THREAD

**Issue by MartiniChauchat** [tamerh/xml-stream-parser#19]
Hey, I started using your library recently. I think there may be an edge case missed in the code
If I test the XML in README, it passes. But if I added an extra space between an attribute name and an opening quote. 
For example
`<bookstore number="2" loc="273456">` is acceptable,
`<bookstore number  ="2" loc="273456">` is also acceptable, 
`<bookstore number=  "2" loc="273456">` throws a runtime error 

Based on [XML spec](https://www.w3.org/TR/xml/#NT-Eq), I think spaces around `=` should be all valid. 
It's probably caused by this line [here](https://github.com/tamerh/xml-stream-parser/blob/master/xmlparser.go#L428)

What do you think?

**Comment by tamerh** [comment]
You're right I think. All white spaces needs to be omitted around `=`

**Comment by tamerh** [comment]
I just released a new version v1.5.0. Issue should be fixed now. Thanks.
