### ISSUE TITLE
CDATA issue

### ISSUE THREAD

**Issue by ramainen** [tamerh/xml-stream-parser#8]
There is a problem while parcing xml document with CDATA block - parsing stops after first element.

Example file:

	<?xml version="1.0" encoding="UTF-8" ?>
	<offers>
		<offer>
			<title>Title1</title>
			<description><![CDATA[Big description 1]]></description>
		</offer>
		<offer>
			<title>Title2</title>
			<description><![CDATA[Big description 2]]></description>
		</offer>
		<offer>
			<title>Title3</title>
			<description><![CDATA[Big description 3]]></description>
		</offer>
	</offers>

Example code:

	import (
		streamParser "github.com/tamerh/xml-stream-parser"
	)
	func main() {
		f, _ := os.Open("example2.xml")
		br := bufio.NewReaderSize(f, 65536)
		parser := streamParser.NewXMLParser(br, "offer")
		for xml := range parser.Stream() {
			for tagName, _:= range xml.Childs {
				fmt.Println(tagName)
			}
		}
	}`

**Comment by tamerh** [comment]
thanks for reporting the issue i was also doubting this might not work. Now added a fix in the master. Check with your data and let me know and i will tag a new version

**Comment by ramainen** [comment]
@tamerh works well both simple text xml, and real-world xml, in production too. You can tag now, thank you very much.

**Comment by tamerh** [comment]
Great that this works and new tag created v1.1.5.
